
name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_SECRET_KEY }}
        script: whoami

#name: UIUC Class Bot
#
#on: [push]
#
#jobs:
#  build:
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: executing remote ssh commands using password
#          uses: appleboy/ssh-action@master
#          with:
#            host: ${{ secrets.HOST }}
#            username: ${{ secrets.USERNAME }}
#            key: ${{ secrets.SSH_SECRET_KEY }}
#            script: |
#              sudo docker pull timot3/uiuc-classes
#              sudo docker stop classbot
#              sudo docker run -itd -e CLASSBOT_TOKEN=$CLASSBOT_TOKEN --rm --name classbot timot3/uiuc-classes
